# Copyright (c) 2026 CuongKenn & ICTU Team
# SPDX-License-Identifier: AGPL-3.0-or-later

"""add id to user_roles

Revision ID: 7a6db0254da0
Revises: a9f01234b567
Create Date: 2026-09-07 16:09:03.324638

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7a6db0254da0"
down_revision: Union[str, None] = "a9f01234b567"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ai_commands", sa.Column("dsl_version", sa.String(length=50), nullable=False)
    )
    op.add_column(
        "ai_commands",
        sa.Column("parameters", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "ai_commands", sa.Column("approved_by_user_id", sa.UUID(), nullable=True)
    )
    op.add_column(
        "ai_commands", sa.Column("second_approver_id", sa.UUID(), nullable=True)
    )
    op.add_column(
        "ai_commands",
        sa.Column("mattermost_message_id", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "ai_commands",
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "ai_commands",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "ai_commands",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
    )
    # Drop indexes tham chieu enum type TRUOC khi alter column type
    # De tranh loi: operator does not exist khi PostgreSQL kiem tra index WHERE clause
    op.drop_index(
        "idx_ai_commands_deadline",
        table_name="ai_commands",
        postgresql_where="(status = 'PENDING_APPROVAL'::ai_command_status)",
    )
    op.drop_index("idx_ai_commands_status", table_name="ai_commands")
    op.drop_index("idx_ai_commands_tenant_id", table_name="ai_commands")

    op.alter_column(
        "ai_commands",
        "effect",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.String(length=50),
        existing_nullable=False,
    )
    op.alter_column(
        "ai_commands",
        "status",
        existing_type=postgresql.ENUM(
            "PENDING_APPROVAL",
            "APPROVED",
            "REJECTED",
            "EXECUTING",
            "COMPLETED",
            "FAILED",
            "TIMEOUT",
            name="ai_command_status",
        ),
        type_=sa.String(length=50),
        existing_nullable=False,
        existing_server_default=sa.text("'PENDING_APPROVAL'::ai_command_status"),
        postgresql_using="status::text",
    )
    op.create_index(
        op.f("ix_ai_commands_deleted_at"), "ai_commands", ["deleted_at"], unique=False
    )
    op.create_index(op.f("ix_ai_commands_id"), "ai_commands", ["id"], unique=False)
    op.create_index(
        op.f("ix_ai_commands_issued_by_user_id"),
        "ai_commands",
        ["issued_by_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_commands_status"), "ai_commands", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_ai_commands_tenant_id"), "ai_commands", ["tenant_id"], unique=False
    )
    op.drop_constraint(
        "ai_commands_approved_by_fkey", "ai_commands", type_="foreignkey"
    )
    op.drop_constraint(
        "ai_commands_second_approver_fkey", "ai_commands", type_="foreignkey"
    )
    op.drop_constraint("ai_commands_tenant_id_fkey", "ai_commands", type_="foreignkey")
    op.drop_constraint(
        "ai_commands_issued_by_user_id_fkey", "ai_commands", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "ai_commands", "users", ["issued_by_user_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None,
        "ai_commands",
        "users",
        ["approved_by_user_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        None,
        "ai_commands",
        "users",
        ["second_approver_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        None, "ai_commands", "tenants", ["tenant_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_table_comment(
        "ai_commands",
        existing_comment="Lịch sử DX-DSL Command. Tách riêng khỏi audit_log để query phê duyệt hiệu quả.",
        schema=None,
    )
    op.drop_column("ai_commands", "session_id")
    op.drop_column("ai_commands", "second_approver")
    op.drop_column("ai_commands", "mattermost_msg_id")
    op.drop_column("ai_commands", "dsl_payload")
    op.drop_column("ai_commands", "approved_by")
    op.add_column("audit_logs", sa.Column("user_id", sa.UUID(), nullable=True))
    op.add_column(
        "audit_logs",
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "audit_logs",
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "audit_logs", sa.Column("status", sa.String(length=50), nullable=False)
    )
    op.add_column(
        "audit_logs",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "audit_logs", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True)
    )
    # Drop indexes audit_logs truoc khi alter
    op.drop_index("idx_audit_logs_created_at", table_name="audit_logs")
    op.drop_index("idx_audit_logs_tenant_id", table_name="audit_logs")

    op.alter_column("audit_logs", "tenant_id", existing_type=sa.UUID(), nullable=True)
    op.alter_column(
        "audit_logs",
        "actor_type",
        existing_type=postgresql.ENUM("HUMAN", "AI_AGENT", "SYSTEM", name="actor_type"),
        type_=sa.String(length=50),
        existing_nullable=False,
        postgresql_using="actor_type::text",
    )
    op.alter_column(
        "audit_logs",
        "resource_type",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.String(length=50),
        nullable=False,
    )
    op.alter_column(
        "audit_logs",
        "ip_address",
        existing_type=postgresql.INET(),
        type_=sa.String(length=45),
        existing_nullable=True,
        postgresql_using="ip_address::text",
    )
    op.create_index(
        op.f("ix_audit_logs_action"), "audit_logs", ["action"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_deleted_at"), "audit_logs", ["deleted_at"], unique=False
    )
    op.create_index(op.f("ix_audit_logs_id"), "audit_logs", ["id"], unique=False)
    op.create_index(
        op.f("ix_audit_logs_tenant_id"), "audit_logs", ["tenant_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_user_id"), "audit_logs", ["user_id"], unique=False
    )
    op.drop_constraint("audit_logs_tenant_id_fkey", "audit_logs", type_="foreignkey")
    op.create_foreign_key(
        None, "audit_logs", "tenants", ["tenant_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "audit_logs", "users", ["user_id"], ["id"], ondelete="SET NULL"
    )
    op.drop_table_comment(
        "audit_logs",
        existing_comment="Immutable audit trail. Không có deleted_at — không được xóa.",
        schema=None,
    )
    op.drop_column("audit_logs", "command_id")
    op.drop_column("audit_logs", "actor_id")
    op.drop_column("audit_logs", "metadata")
    op.add_column(
        "plugins", sa.Column("homepage_url", sa.String(length=1024), nullable=True)
    )
    op.add_column(
        "plugins",
        sa.Column(
            "category",
            sa.String(length=100),
            nullable=False,
            server_default="Utilities",
        ),
    )
    op.add_column(
        "plugins", sa.Column("tags", postgresql.ARRAY(sa.String()), nullable=True)
    )
    op.add_column(
        "plugins",
        sa.Column(
            "screenshots", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.add_column("plugins", sa.Column("long_description", sa.Text(), nullable=True))
    op.add_column(
        "plugins",
        sa.Column(
            "credentials_schema", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.add_column(
        "plugins",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.alter_column(
        "plugins",
        "code_name",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.String(length=255),
        comment=None,
        existing_comment="Định danh duy nhất dạng kebab-case. Dùng làm prefix cho bảng DB của Plugin.",
        existing_nullable=False,
    )
    op.alter_column(
        "plugins",
        "icon_url",
        existing_type=sa.TEXT(),
        type_=sa.String(length=1024),
        existing_nullable=True,
    )
    op.alter_column(
        "plugins",
        "manifest_url",
        existing_type=sa.TEXT(),
        type_=sa.String(length=1024),
        existing_nullable=False,
    )
    op.alter_column(
        "plugins", "author", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.drop_index(
        "idx_plugins_marketplace",
        table_name="plugins",
        postgresql_where="(deleted_at IS NULL)",
    )
    op.drop_constraint("plugins_code_name_key", "plugins", type_="unique")
    op.create_index(op.f("ix_plugins_category"), "plugins", ["category"], unique=False)
    op.create_index(op.f("ix_plugins_code_name"), "plugins", ["code_name"], unique=True)
    op.create_index(
        op.f("ix_plugins_deleted_at"), "plugins", ["deleted_at"], unique=False
    )
    op.create_index(op.f("ix_plugins_id"), "plugins", ["id"], unique=False)
    op.drop_table_comment(
        "plugins",
        existing_comment="Danh mục Plugin trên Marketplace. Mỗi Plugin có 1 manifest.yaml.",
        schema=None,
    )
    op.alter_column("roles", "tenant_id", existing_type=sa.UUID(), nullable=True)
    op.alter_column(
        "roles", "display_name", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.alter_column(
        "roles",
        "permissions",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.drop_index("idx_roles_tenant_id", table_name="roles")
    op.drop_constraint("roles_tenant_id_name_key", "roles", type_="unique")
    op.create_index(op.f("ix_roles_id"), "roles", ["id"], unique=False)
    op.create_index(op.f("ix_roles_tenant_id"), "roles", ["tenant_id"], unique=False)
    op.drop_table_comment(
        "roles",
        existing_comment="Plugin-level roles với fine-grained permissions. Keycloak chỉ lưu tên role.",
        schema=None,
    )
    op.drop_index("idx_tenant_integrations_tenant_id", table_name="tenant_integrations")
    op.create_index(
        op.f("ix_tenant_integrations_deleted_at"),
        "tenant_integrations",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tenant_integrations_id"), "tenant_integrations", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_tenant_integrations_tenant_id"),
        "tenant_integrations",
        ["tenant_id"],
        unique=False,
    )
    # tenant_plugins: Dùng raw SQL idempotent để tránh lỗi khi cột đã tồn tại (hotfix manual)
    op.execute(
        "ALTER TABLE tenant_plugins ADD COLUMN IF NOT EXISTS install_task_id UUID"
    )
    op.execute(
        "ALTER TABLE tenant_plugins ADD COLUMN IF NOT EXISTS install_steps_log JSONB"
    )
    op.execute(
        "ALTER TABLE tenant_plugins ADD COLUMN IF NOT EXISTS credential_ids JSONB"
    )
    op.execute(
        "ALTER TABLE tenant_plugins ADD COLUMN IF NOT EXISTS id UUID DEFAULT gen_random_uuid()"
    )
    op.execute(
        "ALTER TABLE tenant_plugins ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT now()"
    )
    op.execute(
        "ALTER TABLE tenant_plugins ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT now()"
    )
    op.execute(
        "ALTER TABLE tenant_plugins ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ"
    )
    # Cast status ENUM -> VARCHAR (IF COLUMN TYPE IS ENUM)
    op.execute("""
        DO $$
        BEGIN
            IF EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_name='tenant_plugins' AND column_name='status'
                  AND udt_name = 'plugin_status'
            ) THEN
                ALTER TABLE tenant_plugins ALTER COLUMN status TYPE VARCHAR(50) USING status::text;
            END IF;
        END $$;
    """)
    # Drop idx_tenant_plugins_status IF EXISTS
    op.execute("DROP INDEX IF EXISTS idx_tenant_plugins_status")
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_tenant_plugins_deleted_at ON tenant_plugins (deleted_at)"
    )
    op.execute("CREATE INDEX IF NOT EXISTS ix_tenant_plugins_id ON tenant_plugins (id)")
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_tenant_plugins_plugin_id ON tenant_plugins (plugin_id)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_tenant_plugins_tenant_id ON tenant_plugins (tenant_id)"
    )
    op.execute("""
        DO $$ BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM pg_constraint WHERE conname='uq_tenant_plugin'
            ) THEN
                ALTER TABLE tenant_plugins ADD CONSTRAINT uq_tenant_plugin UNIQUE (tenant_id, plugin_id);
            END IF;
        END $$;
    """)
    # Drop FKs IF EXISTS, recreate
    op.execute("""
        DO $$ BEGIN
            IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname='tenant_plugins_plugin_id_fkey') THEN
                ALTER TABLE tenant_plugins DROP CONSTRAINT tenant_plugins_plugin_id_fkey;
            END IF;
        END $$;
    """)
    op.execute("""
        DO $$ BEGIN
            IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname='tenant_plugins_installed_by_user_id_fkey') THEN
                ALTER TABLE tenant_plugins DROP CONSTRAINT tenant_plugins_installed_by_user_id_fkey;
            END IF;
        END $$;
    """)
    op.execute("""
        DO $$ BEGIN
            IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname='tenant_plugins_tenant_id_fkey') THEN
                ALTER TABLE tenant_plugins DROP CONSTRAINT tenant_plugins_tenant_id_fkey;
            END IF;
        END $$;
    """)
    op.execute("""
        DO $$ BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='tenant_plugins_plugin_id_fkey1') THEN
                ALTER TABLE tenant_plugins ADD CONSTRAINT tenant_plugins_plugin_id_fkey1
                FOREIGN KEY (plugin_id) REFERENCES plugins(id) ON DELETE CASCADE;
            END IF;
        END $$;
    """)
    op.execute("""
        DO $$ BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='tenant_plugins_installed_by_user_id_fkey1') THEN
                ALTER TABLE tenant_plugins ADD CONSTRAINT tenant_plugins_installed_by_user_id_fkey1
                FOREIGN KEY (installed_by_user_id) REFERENCES users(id) ON DELETE SET NULL;
            END IF;
        END $$;
    """)
    op.execute("""
        DO $$ BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='tenant_plugins_tenant_id_fkey1') THEN
                ALTER TABLE tenant_plugins ADD CONSTRAINT tenant_plugins_tenant_id_fkey1
                FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
            END IF;
        END $$;
    """)
    # Drop last_updated_at nếu còn tồn tại (đã được xử lý bởi migration khác)
    op.execute("""
        DO $$ BEGIN
            IF EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_name='tenant_plugins' AND column_name='last_updated_at'
            ) THEN
                ALTER TABLE tenant_plugins DROP COLUMN last_updated_at;
            END IF;
        END $$;
    """)
    op.drop_table_comment(
        "tenant_plugins",
        existing_comment="Quan hệ M-N giữa Tenant và Plugin. Ghi nhận trạng thái cài đặt và cấu hình.",
        schema=None,
    )
    op.add_column("tenants", sa.Column("domain", sa.String(length=255), nullable=True))
    op.alter_column(
        "tenants",
        "slug",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.String(length=255),
        comment=None,
        existing_comment="Định danh ngắn gọn, dùng trong URL. Ví dụ: app.proteus.io/t/ictu",
        existing_nullable=False,
    )
    op.alter_column(
        "tenants",
        "keycloak_realm",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.String(length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "tenants",
        "deleted_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="Soft delete — NULL = còn hoạt động, NOT NULL = đã bị xóa.",
        existing_nullable=True,
    )
    op.drop_constraint("tenants_slug_key", "tenants", type_="unique")
    op.create_index(
        op.f("ix_tenants_deleted_at"), "tenants", ["deleted_at"], unique=False
    )
    op.create_index(op.f("ix_tenants_domain"), "tenants", ["domain"], unique=True)
    op.create_index(op.f("ix_tenants_id"), "tenants", ["id"], unique=False)
    op.create_index(op.f("ix_tenants_slug"), "tenants", ["slug"], unique=True)
    op.drop_table_comment(
        "tenants",
        existing_comment="Bảng lưu thông tin Tenant (Tổ chức). Mỗi Tenant có 1 Keycloak Realm riêng.",
        schema=None,
    )
    op.drop_index("idx_user_roles_role_id", table_name="user_roles")
    op.drop_index("idx_user_roles_user_id", table_name="user_roles")
    op.drop_constraint("user_roles_user_role_key", "user_roles", type_="unique")
    op.create_index(
        op.f("ix_user_roles_deleted_at"), "user_roles", ["deleted_at"], unique=False
    )
    op.create_index(op.f("ix_user_roles_id"), "user_roles", ["id"], unique=False)
    op.create_index(
        op.f("ix_user_roles_role_id"), "user_roles", ["role_id"], unique=False
    )
    op.create_index(
        op.f("ix_user_roles_user_id"), "user_roles", ["user_id"], unique=False
    )
    op.drop_table_comment(
        "user_roles",
        existing_comment="Phân quyền cụ thể của người dùng trong Tenant.",
        schema=None,
    )
    op.alter_column("users", "keycloak_id", existing_type=sa.UUID(), nullable=False)
    op.alter_column(
        "users", "full_name", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.alter_column(
        "users",
        "avatar_url",
        existing_type=sa.TEXT(),
        type_=sa.String(length=1024),
        existing_nullable=True,
    )
    op.drop_index("idx_users_email", table_name="users")
    op.drop_index("idx_users_tenant_id", table_name="users")
    op.drop_constraint("users_keycloak_id_key", "users", type_="unique")
    op.drop_constraint("users_tenant_id_email_key", "users", type_="unique")
    op.create_index(op.f("ix_users_deleted_at"), "users", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=False)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_keycloak_id"), "users", ["keycloak_id"], unique=True)
    op.create_index(op.f("ix_users_tenant_id"), "users", ["tenant_id"], unique=False)
    op.drop_constraint("users_tenant_id_fkey", "users", type_="foreignkey")
    op.create_foreign_key(
        None, "users", "tenants", ["tenant_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_table_comment(
        "users",
        existing_comment="Mirror của Keycloak User. ID đồng bộ với sub claim trong JWT.",
        schema=None,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        "users",
        "Mirror của Keycloak User. ID đồng bộ với sub claim trong JWT.",
        existing_comment=None,
        schema=None,
    )
    op.drop_constraint(None, "users", type_="foreignkey")
    op.create_foreign_key(
        "users_tenant_id_fkey",
        "users",
        "tenants",
        ["tenant_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.drop_index(op.f("ix_users_tenant_id"), table_name="users")
    op.drop_index(op.f("ix_users_keycloak_id"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_deleted_at"), table_name="users")
    op.create_unique_constraint(
        "users_tenant_id_email_key", "users", ["tenant_id", "email"]
    )
    op.create_unique_constraint("users_keycloak_id_key", "users", ["keycloak_id"])
    op.create_index("idx_users_tenant_id", "users", ["tenant_id"], unique=False)
    op.create_index("idx_users_email", "users", ["email"], unique=False)
    op.alter_column(
        "users",
        "avatar_url",
        existing_type=sa.String(length=1024),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "users", "full_name", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.alter_column("users", "keycloak_id", existing_type=sa.UUID(), nullable=True)
    op.create_table_comment(
        "user_roles",
        "Phân quyền cụ thể của người dùng trong Tenant.",
        existing_comment=None,
        schema=None,
    )
    op.drop_index(op.f("ix_user_roles_user_id"), table_name="user_roles")
    op.drop_index(op.f("ix_user_roles_role_id"), table_name="user_roles")
    op.drop_index(op.f("ix_user_roles_id"), table_name="user_roles")
    op.drop_index(op.f("ix_user_roles_deleted_at"), table_name="user_roles")
    op.create_unique_constraint(
        "user_roles_user_role_key", "user_roles", ["user_id", "role_id"]
    )
    op.create_index("idx_user_roles_user_id", "user_roles", ["user_id"], unique=False)
    op.create_index("idx_user_roles_role_id", "user_roles", ["role_id"], unique=False)
    op.create_table_comment(
        "tenants",
        "Bảng lưu thông tin Tenant (Tổ chức). Mỗi Tenant có 1 Keycloak Realm riêng.",
        existing_comment=None,
        schema=None,
    )
    op.drop_index(op.f("ix_tenants_slug"), table_name="tenants")
    op.drop_index(op.f("ix_tenants_id"), table_name="tenants")
    op.drop_index(op.f("ix_tenants_domain"), table_name="tenants")
    op.drop_index(op.f("ix_tenants_deleted_at"), table_name="tenants")
    op.create_unique_constraint("tenants_slug_key", "tenants", ["slug"])
    op.alter_column(
        "tenants",
        "deleted_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Soft delete — NULL = còn hoạt động, NOT NULL = đã bị xóa.",
        existing_nullable=True,
    )
    op.alter_column(
        "tenants",
        "keycloak_realm",
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=100),
        existing_nullable=False,
    )
    op.alter_column(
        "tenants",
        "slug",
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=100),
        comment="Định danh ngắn gọn, dùng trong URL. Ví dụ: app.proteus.io/t/ictu",
        existing_nullable=False,
    )
    op.drop_column("tenants", "domain")
    op.add_column(
        "tenant_plugins",
        sa.Column(
            "last_updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.create_table_comment(
        "tenant_plugins",
        "Quan hệ M-N giữa Tenant và Plugin. Ghi nhận trạng thái cài đặt và cấu hình.",
        existing_comment=None,
        schema=None,
    )
    op.drop_constraint(None, "tenant_plugins", type_="foreignkey")
    op.drop_constraint(None, "tenant_plugins", type_="foreignkey")
    op.drop_constraint(None, "tenant_plugins", type_="foreignkey")
    op.create_foreign_key(
        "tenant_plugins_tenant_id_fkey",
        "tenant_plugins",
        "tenants",
        ["tenant_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        "tenant_plugins_installed_by_user_id_fkey",
        "tenant_plugins",
        "users",
        ["installed_by_user_id"],
        ["id"],
    )
    op.create_foreign_key(
        "tenant_plugins_plugin_id_fkey",
        "tenant_plugins",
        "plugins",
        ["plugin_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.drop_constraint("uq_tenant_plugin", "tenant_plugins", type_="unique")
    op.drop_index(op.f("ix_tenant_plugins_tenant_id"), table_name="tenant_plugins")
    op.drop_index(op.f("ix_tenant_plugins_plugin_id"), table_name="tenant_plugins")
    op.drop_index(op.f("ix_tenant_plugins_id"), table_name="tenant_plugins")
    op.drop_index(op.f("ix_tenant_plugins_deleted_at"), table_name="tenant_plugins")
    op.create_index(
        "idx_tenant_plugins_status", "tenant_plugins", ["status"], unique=False
    )
    op.alter_column(
        "tenant_plugins",
        "installed_version",
        existing_type=sa.VARCHAR(length=50),
        nullable=True,
    )
    op.alter_column(
        "tenant_plugins",
        "status",
        existing_type=sa.String(length=50),
        type_=postgresql.ENUM(
            "INSTALLING",
            "ACTIVE",
            "FAILED_DIRTY",
            "DISABLED",
            "UNINSTALLING",
            "DELETED",
            name="plugin_status",
        ),
        existing_nullable=False,
        existing_server_default=sa.text("'INSTALLING'::plugin_status"),
    )
    op.drop_column("tenant_plugins", "deleted_at")
    op.drop_column("tenant_plugins", "updated_at")
    op.drop_column("tenant_plugins", "created_at")
    op.drop_column("tenant_plugins", "id")
    op.drop_column("tenant_plugins", "credential_ids")
    op.drop_column("tenant_plugins", "install_steps_log")
    op.drop_column("tenant_plugins", "install_task_id")
    op.drop_index(
        op.f("ix_tenant_integrations_tenant_id"), table_name="tenant_integrations"
    )
    op.drop_index(op.f("ix_tenant_integrations_id"), table_name="tenant_integrations")
    op.drop_index(
        op.f("ix_tenant_integrations_deleted_at"), table_name="tenant_integrations"
    )
    op.create_index(
        "idx_tenant_integrations_tenant_id",
        "tenant_integrations",
        ["tenant_id"],
        unique=False,
    )
    op.create_table_comment(
        "roles",
        "Plugin-level roles với fine-grained permissions. Keycloak chỉ lưu tên role.",
        existing_comment=None,
        schema=None,
    )
    op.drop_index(op.f("ix_roles_tenant_id"), table_name="roles")
    op.drop_index(op.f("ix_roles_id"), table_name="roles")
    op.create_unique_constraint(
        "roles_tenant_id_name_key", "roles", ["tenant_id", "name"]
    )
    op.create_index("idx_roles_tenant_id", "roles", ["tenant_id"], unique=False)
    op.alter_column(
        "roles",
        "permissions",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.alter_column(
        "roles", "display_name", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.alter_column("roles", "tenant_id", existing_type=sa.UUID(), nullable=False)
    op.create_table_comment(
        "plugins",
        "Danh mục Plugin trên Marketplace. Mỗi Plugin có 1 manifest.yaml.",
        existing_comment=None,
        schema=None,
    )
    op.drop_index(op.f("ix_plugins_id"), table_name="plugins")
    op.drop_index(op.f("ix_plugins_deleted_at"), table_name="plugins")
    op.drop_index(op.f("ix_plugins_code_name"), table_name="plugins")
    op.drop_index(op.f("ix_plugins_category"), table_name="plugins")
    op.create_unique_constraint("plugins_code_name_key", "plugins", ["code_name"])
    op.create_index(
        "idx_plugins_marketplace",
        "plugins",
        [sa.text("is_official DESC"), sa.text("download_count DESC")],
        unique=False,
        postgresql_where="(deleted_at IS NULL)",
    )
    op.alter_column(
        "plugins", "author", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.alter_column(
        "plugins",
        "manifest_url",
        existing_type=sa.String(length=1024),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.alter_column(
        "plugins",
        "icon_url",
        existing_type=sa.String(length=1024),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "plugins",
        "code_name",
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=100),
        comment="Định danh duy nhất dạng kebab-case. Dùng làm prefix cho bảng DB của Plugin.",
        existing_nullable=False,
    )
    op.drop_column("plugins", "created_at")
    op.drop_column("plugins", "credentials_schema")
    op.drop_column("plugins", "long_description")
    op.drop_column("plugins", "screenshots")
    op.drop_column("plugins", "tags")
    op.drop_column("plugins", "category")
    op.drop_column("plugins", "homepage_url")
    op.add_column(
        "audit_logs",
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "audit_logs",
        sa.Column("actor_id", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "audit_logs",
        sa.Column(
            "command_id",
            sa.UUID(),
            autoincrement=False,
            nullable=True,
            comment="Nếu do AI Agent thực hiện, trỏ đến bản ghi AI_COMMAND tương ứng.",
        ),
    )
    op.create_table_comment(
        "audit_logs",
        "Immutable audit trail. Không có deleted_at — không được xóa.",
        existing_comment=None,
        schema=None,
    )
    op.drop_constraint(None, "audit_logs", type_="foreignkey")
    op.drop_constraint(None, "audit_logs", type_="foreignkey")
    op.create_foreign_key(
        "audit_logs_tenant_id_fkey",
        "audit_logs",
        "tenants",
        ["tenant_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.drop_index(op.f("ix_audit_logs_user_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_tenant_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_deleted_at"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_action"), table_name="audit_logs")
    op.create_index(
        "idx_audit_logs_tenant_id", "audit_logs", ["tenant_id"], unique=False
    )
    op.create_index(
        "idx_audit_logs_created_at",
        "audit_logs",
        [sa.text("created_at DESC")],
        unique=False,
    )
    op.alter_column(
        "audit_logs",
        "ip_address",
        existing_type=sa.String(length=45),
        type_=postgresql.INET(),
        existing_nullable=True,
    )
    op.alter_column(
        "audit_logs",
        "resource_type",
        existing_type=sa.String(length=50),
        type_=sa.VARCHAR(length=100),
        nullable=True,
    )
    op.alter_column(
        "audit_logs",
        "actor_type",
        existing_type=sa.String(length=50),
        type_=postgresql.ENUM("HUMAN", "AI_AGENT", "SYSTEM", name="actor_type"),
        existing_nullable=False,
    )
    op.alter_column("audit_logs", "tenant_id", existing_type=sa.UUID(), nullable=False)
    op.drop_column("audit_logs", "deleted_at")
    op.drop_column("audit_logs", "updated_at")
    op.drop_column("audit_logs", "status")
    op.drop_column("audit_logs", "result")
    op.drop_column("audit_logs", "payload")
    op.drop_column("audit_logs", "user_id")
    op.add_column(
        "ai_commands",
        sa.Column("approved_by", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "ai_commands",
        sa.Column(
            "dsl_payload",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "ai_commands",
        sa.Column(
            "mattermost_msg_id",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "ai_commands",
        sa.Column("second_approver", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "ai_commands",
        sa.Column("session_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.create_table_comment(
        "ai_commands",
        "Lịch sử DX-DSL Command. Tách riêng khỏi audit_log để query phê duyệt hiệu quả.",
        existing_comment=None,
        schema=None,
    )
    op.drop_constraint(None, "ai_commands", type_="foreignkey")
    op.drop_constraint(None, "ai_commands", type_="foreignkey")
    op.drop_constraint(None, "ai_commands", type_="foreignkey")
    op.drop_constraint(None, "ai_commands", type_="foreignkey")
    op.create_foreign_key(
        "ai_commands_issued_by_user_id_fkey",
        "ai_commands",
        "users",
        ["issued_by_user_id"],
        ["id"],
    )
    op.create_foreign_key(
        "ai_commands_tenant_id_fkey",
        "ai_commands",
        "tenants",
        ["tenant_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        "ai_commands_second_approver_fkey",
        "ai_commands",
        "users",
        ["second_approver"],
        ["id"],
    )
    op.create_foreign_key(
        "ai_commands_approved_by_fkey", "ai_commands", "users", ["approved_by"], ["id"]
    )
    op.drop_index(op.f("ix_ai_commands_tenant_id"), table_name="ai_commands")
    op.drop_index(op.f("ix_ai_commands_status"), table_name="ai_commands")
    op.drop_index(op.f("ix_ai_commands_issued_by_user_id"), table_name="ai_commands")
    op.drop_index(op.f("ix_ai_commands_id"), table_name="ai_commands")
    op.drop_index(op.f("ix_ai_commands_deleted_at"), table_name="ai_commands")
    op.create_index(
        "idx_ai_commands_tenant_id", "ai_commands", ["tenant_id"], unique=False
    )
    op.create_index("idx_ai_commands_status", "ai_commands", ["status"], unique=False)
    op.create_index(
        "idx_ai_commands_deadline",
        "ai_commands",
        ["approval_deadline"],
        unique=False,
        postgresql_where="(status = 'PENDING_APPROVAL'::ai_command_status)",
    )
    op.alter_column(
        "ai_commands",
        "status",
        existing_type=sa.String(length=50),
        type_=postgresql.ENUM(
            "PENDING_APPROVAL",
            "APPROVED",
            "REJECTED",
            "EXECUTING",
            "COMPLETED",
            "FAILED",
            "TIMEOUT",
            name="ai_command_status",
        ),
        existing_nullable=False,
        existing_server_default=sa.text("'PENDING_APPROVAL'::ai_command_status"),
    )
    op.alter_column(
        "ai_commands",
        "effect",
        existing_type=sa.String(length=50),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
    )
    op.drop_column("ai_commands", "deleted_at")
    op.drop_column("ai_commands", "updated_at")
    op.drop_column("ai_commands", "approved_at")
    op.drop_column("ai_commands", "mattermost_message_id")
    op.drop_column("ai_commands", "second_approver_id")
    op.drop_column("ai_commands", "approved_by_user_id")
    op.drop_column("ai_commands", "parameters")
    op.drop_column("ai_commands", "dsl_version")
    # ### end Alembic commands ###
