# Copyright (c) 2026 CuongKenn & ICTU Team
# SPDX-License-Identifier: AGPL-3.0-or-later

"""add soft delete to audit_logs and user_roles

Revision ID: d8a02bcff25d
Revises: 5b760b94e612
Create Date: 2026-08-11 13:22:56.169100

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d8a02bcff25d"
down_revision: str | None = "5b760b94e612"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "audit_logs", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.create_index(
        op.f("ix_audit_logs_deleted_at"), "audit_logs", ["deleted_at"], unique=False
    )

    op.add_column(
        "user_roles", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.create_index(
        op.f("ix_user_roles_deleted_at"), "user_roles", ["deleted_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_roles_deleted_at"), table_name="user_roles")
    op.drop_column("user_roles", "deleted_at")

    op.drop_index(op.f("ix_audit_logs_deleted_at"), table_name="audit_logs")
    op.drop_column("audit_logs", "deleted_at")
    # ### end Alembic commands ###
