# Copyright (c) 2026 CuongKenn & ICTU Team
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# AI Engine - Autonomous Plugin Synthesizer
# Dịch yêu cầu ngôn ngữ tự nhiên thành một plugin hoàn chỉnh.

import json
import logging
import os
import re
from pathlib import Path

from langchain_core.prompts import ChatPromptTemplate
from langchain_openai import ChatOpenAI

from app.infrastructure.config import settings

logger = logging.getLogger(__name__)


class PluginSynthesizer:
    def __init__(self):
        self._plugins_dir = Path(settings.PLUGINS_DIR)
        if not self._plugins_dir.is_absolute():
            backend_dir = Path(__file__).parent.parent.parent.parent
            root_dir = backend_dir.parent.parent
            self._plugins_dir = (root_dir / settings.PLUGINS_DIR).resolve()

        # Dung settings thay vi os.getenv truc tiep
        if not settings.OPENAI_API_KEY:
            logger.warning("OPENAI_API_KEY chua duoc cau hinh, PluginSynthesizer se dung mock mode")
            self.llm = None
        else:
            model_name = getattr(settings, "LLM_MODEL_NAME", "gpt-4o")
            self.llm = ChatOpenAI(model=model_name, api_key=settings.OPENAI_API_KEY)

    async def synthesize(self, prompt: str) -> str:
        """
        Nhận một prompt (VD: 'Tạo plugin quản lý bệnh viện với chức năng khám bệnh')
        và tự động sinh mã nguồn (manifest.yaml, migrations) cho plugin đó.
        """
        logger.info("Synthesizing plugin from prompt: %s", prompt)

        system_prompt = """
        Bạn là Proteus OS AI Plugin Synthesizer.
        Hãy tạo một Plugin cho hệ thống dựa trên yêu cầu của người dùng.
        
        Hệ thống yêu cầu trả về ĐÚNG MỘT JSON hợp lệ (không markdown) với cấu trúc sau:
        {
            "code_name": "tên-plugin-khong-dau",
            "manifest_yaml": "nội dung file manifest.yaml",
            "seed_sql": "nội dung file db/seed_data.sql chứa CREATE TABLE",
            "python_main": "nội dung file main.py (tùy chọn, để rỗng nếu không cần)"
        }
        
        Quy tắc manifest.yaml:
        - version: '1.0.0'
        - spec_version: '1.1.0'
        - Phải có phần database.tables (danh sách các bảng).
        
        Quy tắc seed_sql:
        - Phải dùng PostgreSQL.
        - Không được có cột tenant_id (hệ thống sẽ tự tiêm).
        """

        chat_prompt = ChatPromptTemplate.from_messages(
            [("system", system_prompt), ("human", prompt)]
        )

        chain = chat_prompt | self.llm

        try:
            # Fallback mock for testing without API Key
            if os.getenv("OPENAI_API_KEY", "dummy") == "dummy":
                return self._mock_synthesize(prompt)

            response = await chain.ainvoke({})
            content = response.content

            # Clean markdown if generated
            content = re.sub(r"^```json", "", content)
            content = re.sub(r"```$", "", content).strip()

            data = json.loads(content)

            plugin_name = data.get("code_name", "unknown-plugin")
            self._write_plugin_files(plugin_name, data)

            return plugin_name

        except Exception as e:
            logger.error("Error synthesizing plugin: %s", e, exc_info=True)
            raise e

    def _write_plugin_files(self, plugin_name: str, data: dict) -> None:
        plugin_path = self._plugins_dir / plugin_name
        plugin_path.mkdir(parents=True, exist_ok=True)

        manifest_content = data.get("manifest_yaml", "")
        with open(plugin_path / "manifest.yaml", "w", encoding="utf-8") as f:
            f.write(manifest_content)

        db_path = plugin_path / "db"
        db_path.mkdir(exist_ok=True)

        seed_sql = data.get("seed_sql", "")
        if seed_sql:
            with open(db_path / "seed_data.sql", "w", encoding="utf-8") as f:
                f.write(seed_sql)

        python_main = data.get("python_main", "")
        if python_main:
            with open(plugin_path / "main.py", "w", encoding="utf-8") as f:
                f.write(python_main)

        logger.info("Successfully generated plugin files at %s", plugin_path)

    def _mock_synthesize(self, prompt: str) -> str:
        """Mock behavior cho CI/CD khi không có OPENAI_API_KEY"""
        plugin_name = (
            "hospital-module" if "bệnh viện" in prompt.lower() else "demo-module"
        )

        data = {
            "code_name": plugin_name,
            "manifest_yaml": f"name: {plugin_name}\\nversion: '1.0.0'\\nspec_version: '1.1.0'\\ndescription: 'Generated by AI'",
            "seed_sql": f"CREATE TABLE {plugin_name.replace('-', '_')}_records (id SERIAL PRIMARY KEY, name VARCHAR(100));",
            "python_main": "import logging\nlogger = logging.getLogger(__name__)\n\ndef register_plugin(app):\n    logger.info('Mock plugin registered')\n",
        }

        self._write_plugin_files(plugin_name, data)
        return plugin_name
